### ISSUE TITLE
The addon __init__.py crashes

### ISSUE THREAD

**Issue by hehe2** [GDQuest/blender-power-sequencer#474]
- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**

I was trying to use a blender script to render a video.

There is this message :

Exception in module register(): D:\tools\blender\3.6\scripts\addons\power_sequencer\__init__.py
Traceback (most recent call last):
  File "D:\tools\blender\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "D:\tools\blender\3.6\scripts\addons\power_sequencer\__init__.py", line 62, in register
    bpy.utils.register_tool(cls, after=last_tool, separator=index == 0)
  File "D:\tools\blender\3.6\scripts\modules\bpy\utils\__init__.py", line 875, in register_tool
    tool_converted = tool_from_class(tool_cls)
  File "D:\tools\blender\3.6\scripts\modules\bpy\utils\__init__.py", line 872, in tool_from_class
    cls._km_action_simple(kc_default, kc, context_descr, tool_def.label, keymap_data)
  File "D:\tools\blender\3.6\scripts\startup\bl_ui\space_toolsystem_common.py", line 488, in _km_action_simple
    km = kc.keymaps.get(km_idname)
AttributeError: 'NoneType' object has no attribute 'keymaps'

**What is the expected behavior?**

Well, I guess I shouldn't get any exception...

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

Well, I'm using a VSE render script I got there https://github.com/mikeycal/the-video-editors-render-script-for-blender

It used to work with the 2.8.x version but I've updated to 3.6 and installed power sequencer and I got this error (note: I had to tweak the script a bit for it to work with Blender 3.6.x versions)

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

Thanks for your help =)

**Other information**
